version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sofiegraham/docker-node-test:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1" # limiting each replica to use, at most, 10% of the CPU (across all cores), and 50MB of RAM.
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:7777"
    networks: # this is the load balanced network called webnet # if you use the overlay network, but you could also remove the service networks configuration to bypass that. Then you would have to publish the port of the service you want to expose.
      - webnet
    environment:
      SERVER_PORT: 7777
      POSTGRES_DB: dockerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
     - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_PASSWORD: password123
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: